Add ability to step down
gravitational/coordinate pull request #5
Opened 2017-03-01 21:19 UTC by r0mant

2017-03-01 21:20 UTC, klizhentas approved these changes

2017-03-02 20:33 UTC, klizhentas requested changes
hey, while you are on it, can you move Info to debug everywhere here? It is extremely chatty because of this info statements.

2017-03-02 22:12 UTC, r0mant commented
@klizhentas Sure, updated.

2017-03-02 22:41 UTC, klizhentas approved these changes

2017-03-03 01:01 UTC, merged